/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = 1;
export type GeneratedAt = string;
export type Currency = string;
export type Years = number[];
export type MonthKeys = string[];
export type TransactionCount = number;
export type Start = string;
export type End = string;
export type Categories = string[];
export type Name = string;
export type Institution = string | null;
export type Color = string | null;
export type Spending = boolean;
export type Income = boolean;
export type Networth = boolean;
export type Year = number;
export type Spent = number;
export type Income1 = number;
export type Saved = number;
export type ByYear = YearSpend[];
export type Category = string;
export type Amount = number;
export type AllTimeByCategory = CategoryAmount[];
export type TotalSpent = number;
export type TotalIncome = number;
export type Month = number;
export type Income2 = number;
export type Matrix = MonthMatrixRow[];
export type TotalSpent1 = number;
export type TotalIncome1 = number;
export type ByCategory = CategoryAmount[];
export type Date = string;
export type Payee = string;
export type Amount1 = number;
export type Category1 = string;
export type Source = string | null;
export type Pending = boolean;
export type Locator = string;
export type Bill = number | null;
export type Transactions = Txn[];
export type Date1 = string;
export type Payee1 = string;
export type Employer = string | null;
export type Gross = number;
export type Net = number;
export type TakeHome = number;
export type Locator1 = string;
export type Paychecks = PaycheckOut[];
export type Date2 = string;
export type Payee2 = string;
export type Amount2 = number;
export type FromAccount = string;
export type ToAccount = string;
export type Pending1 = boolean;
export type Locator2 = string;
export type Transfers = Transfer[];
export type Year1 = number;
export type Gross1 = number;
export type Net1 = number;
export type TakeHome1 = number;
export type Deductions1 = number;
export type Contributions1 = number;
export type ByYear1 = IncomeYear[];
export type RecentPaychecks = PaycheckOut[];
export type Date3 = string;
export type Assets = number;
export type Liabilities = number;
export type NetWorth = number;
export type Series = NetWorthSnapshot[];
export type Account = string;
export type Label = string;
export type Group = string;
export type Bucket = string;
export type Value = number;
export type Accounts1 = NetWorthAccount[];
export type Account1 = string;
export type Label1 = string;
export type Value1 = number;
export type Adjustments = NetWorthAdjustment[];
export type Swr = number;
export type RealReturn = number;
export type RetireAge = number;
export type RunwayTarget = number;
export type BirthYear = number | null;
export type SettingSpecs = SettingField[] | null;
export type Key = string;
export type Label2 = string;
export type Kind = 'percent' | 'age' | 'year' | 'months';
export type Min = number;
export type Max = number;
export type Default = number | null;
export type Help = string;
export type SpendingCategories = string[];
export type FundingAccounts = string[];
export type Employers = string[];
export type Kind1 = 'deduction' | 'contribution';
export type Label3 = string;
export type Employer1 = string | null;
export type Account2 = string;
export type PayrollOptions = PayrollOption[];
export type CashAccounts = string[];
export type CreditAccounts = string[];
export type InvestmentAccounts = string[];
export type BalanceAccounts = string[];
export type LiabilityAccounts = string[];

export interface DashboardData {
	schema_version: SchemaVersion;
	generated_at: GeneratedAt;
	currency: Currency;
	meta: Meta;
	overview: Overview;
	years: Years1;
	months: Months;
	income: IncomeSection;
	networth?: NetWorthSection | null;
	settings?: SettingsSection | null;
	setting_specs?: SettingSpecs;
	account_lists?: AccountLists | null;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "Meta".
 */
export interface Meta {
	years: Years;
	month_keys: MonthKeys;
	transaction_count: TransactionCount;
	date_range: DateRange | null;
	categories: Categories;
	accounts: Accounts;
	domains: Domains;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "DateRange".
 */
export interface DateRange {
	start: Start;
	end: End;
}
export interface Accounts {
	[k: string]: AccountInfo;
}
/**
 * How one account presents itself: its display name and who holds it.
 *
 * Both are resolved from ledger metadata by :mod:`yala.ledger.naming`, so the frontend looks a
 * name up rather than deriving it. That keeps one implementation of the naming rule instead of
 * one per language, and it means the ledger stays the only place that decides what an account is
 * called.
 *
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "AccountInfo".
 */
export interface AccountInfo {
	name: Name;
	institution?: Institution;
	color?: Color;
}
/**
 * Which domains carry data.
 *
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "Domains".
 */
export interface Domains {
	spending: Spending;
	income: Income;
	networth?: Networth;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "Overview".
 */
export interface Overview {
	by_year: ByYear;
	all_time_by_category: AllTimeByCategory;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "YearSpend".
 */
export interface YearSpend {
	year: Year;
	spent: Spent;
	income: Income1;
	saved: Saved;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "CategoryAmount".
 */
export interface CategoryAmount {
	category: Category;
	amount: Amount;
}
export interface Years1 {
	[k: string]: YearPage;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "YearPage".
 */
export interface YearPage {
	total_spent: TotalSpent;
	total_income: TotalIncome;
	matrix: Matrix;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "MonthMatrixRow".
 */
export interface MonthMatrixRow {
	month: Month;
	spent: Spent1;
	income: Income2;
}
export interface Spent1 {
	[k: string]: number;
}
export interface Months {
	[k: string]: MonthPage;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "MonthPage".
 */
export interface MonthPage {
	total_spent: TotalSpent1;
	total_income: TotalIncome1;
	by_category: ByCategory;
	transactions: Transactions;
	paychecks: Paychecks;
	transfers?: Transfers;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "Txn".
 */
export interface Txn {
	date: Date;
	payee: Payee;
	amount: Amount1;
	category: Category1;
	source: Source;
	pending: Pending;
	locator: Locator;
	bill?: Bill;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "PaycheckOut".
 */
export interface PaycheckOut {
	date: Date1;
	payee: Payee1;
	employer?: Employer;
	gross: Gross;
	deductions: Deductions;
	contributions: Contributions;
	net: Net;
	take_home: TakeHome;
	locator: Locator1;
}
export interface Deductions {
	[k: string]: number;
}
export interface Contributions {
	[k: string]: number;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "Transfer".
 */
export interface Transfer {
	date: Date2;
	payee: Payee2;
	amount: Amount2;
	from_account: FromAccount;
	to_account: ToAccount;
	pending: Pending1;
	locator: Locator2;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "IncomeSection".
 */
export interface IncomeSection {
	by_year: ByYear1;
	by_month: ByMonth;
	recent_paychecks: RecentPaychecks;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "IncomeYear".
 */
export interface IncomeYear {
	year: Year1;
	gross: Gross1;
	net: Net1;
	take_home: TakeHome1;
	deductions: Deductions1;
	contributions: Contributions1;
}
export interface ByMonth {
	[k: string]: number[];
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "NetWorthSection".
 */
export interface NetWorthSection {
	current: NetWorthSnapshot | null;
	series: Series;
	accounts: Accounts1;
	adjustments: Adjustments;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "NetWorthSnapshot".
 */
export interface NetWorthSnapshot {
	date: Date3;
	assets: Assets;
	liabilities: Liabilities;
	net_worth: NetWorth;
	breakdown: Breakdown;
}
export interface Breakdown {
	[k: string]: number;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "NetWorthAccount".
 */
export interface NetWorthAccount {
	account: Account;
	label: Label;
	group: Group;
	bucket: Bucket;
	value: Value;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "NetWorthAdjustment".
 */
export interface NetWorthAdjustment {
	account: Account1;
	label: Label1;
	value: Value1;
}
/**
 * Effective user settings: what the ledger states, else the built-in default.
 *
 * A null means the setting is unset and has no default — features depending on it stay hidden
 * rather than guessing. Keys mirror :data:`yala.ledger.settings.SETTINGS`; ``test_settings``
 * asserts the two can't drift.
 *
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "SettingsSection".
 */
export interface SettingsSection {
	swr: Swr;
	real_return: RealReturn;
	retire_age: RetireAge;
	runway_target: RunwayTarget;
	birth_year?: BirthYear;
}
/**
 * The spec behind one setting: how the form names it, bounds it, and explains it.
 *
 * Snapshotted alongside the values so the settings form renders with no API running — the same
 * rule every other form follows. Writing one still needs the API, and the frontend's single write
 * guard is what says so.
 *
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "SettingField".
 */
export interface SettingField {
	key: Key;
	label: Label2;
	kind: Kind;
	min: Min;
	max: Max;
	default: Default;
	help: Help;
}
/**
 * The pickable account sets the entry forms and the Manage panels choose from.
 *
 * Snapshotted into ``data.json`` as well as served live from ``/api/accounts`` (both from one
 * builder function) so the forms still render — and Manage still lists what you have — when the
 * local API is down. Writes are refused by the frontend's single write guard, not by an absent
 * list: a form that vanishes reads as a missing feature rather than as an unreachable server.
 *
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "AccountLists".
 */
export interface AccountLists {
	spending_categories: SpendingCategories;
	funding_accounts: FundingAccounts;
	employers: Employers;
	payroll_options: PayrollOptions;
	cash_accounts: CashAccounts;
	credit_accounts: CreditAccounts;
	investment_accounts: InvestmentAccounts;
	balance_accounts: BalanceAccounts;
	liability_accounts: LiabilityAccounts;
	sweeps: Sweeps;
}
/**
 * One selectable paycheck line, scoped to an employer (null = offered by every employer).
 *
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "PayrollOption".
 */
export interface PayrollOption {
	kind: Kind1;
	label: Label3;
	employer: Employer1;
	account: Account2;
}
export interface Sweeps {
	[k: string]: string;
}
