/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = 1;
export type GeneratedAt = string;
export type Currency = string;
export type Years = number[];
export type MonthKeys = string[];
export type TransactionCount = number;
export type Start = string;
export type End = string;
export type Categories = string[];
export type Spending = boolean;
export type Income = boolean;
export type Networth = boolean;
export type Investments = boolean;
export type Cards = boolean;
export type Year = number;
export type Spent = number;
export type Income1 = number;
export type Saved = number;
export type ByYear = YearSpend[];
export type Category = string;
export type Amount = number;
export type AllTimeByCategory = CategoryAmount[];
export type TotalSpent = number;
export type TotalIncome = number;
export type Month = number;
export type Income2 = number;
export type Matrix = MonthMatrixRow[];
export type TotalSpent1 = number;
export type TotalIncome1 = number;
export type ByCategory = CategoryAmount[];
export type Date = string;
export type Payee = string;
export type Amount1 = number;
export type Category1 = string;
export type Source = string | null;
export type Pending = boolean;
export type Locator = string;
export type Bill = number | null;
export type Transactions = Txn[];
export type Date1 = string;
export type Payee1 = string;
export type Employer = string | null;
export type Gross = number;
export type Net = number;
export type TakeHome = number;
export type Locator1 = string;
export type Paychecks = PaycheckOut[];
export type Date2 = string;
export type Payee2 = string;
export type Amount2 = number;
export type FromAccount = string;
export type ToAccount = string;
export type Pending1 = boolean;
export type Locator2 = string;
export type Transfers = Transfer[];
export type Year1 = number;
export type Gross1 = number;
export type Net1 = number;
export type TakeHome1 = number;
export type Deductions1 = number;
export type Contributions1 = number;
export type ByYear1 = IncomeYear[];
export type RecentPaychecks = PaycheckOut[];
export type Cards1 = unknown[];

export interface DashboardData {
	schema_version: SchemaVersion;
	generated_at: GeneratedAt;
	currency: Currency;
	meta: Meta;
	overview: Overview;
	years: Years1;
	months: Months;
	income: IncomeSection;
	networth?: NetWorthSection | null;
	investments?: InvestmentsSection | null;
	cards?: Cards1;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "Meta".
 */
export interface Meta {
	years: Years;
	month_keys: MonthKeys;
	transaction_count: TransactionCount;
	date_range: DateRange | null;
	categories: Categories;
	domains: Domains;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "DateRange".
 */
export interface DateRange {
	start: Start;
	end: End;
}
/**
 * Which domains carry data.
 *
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "Domains".
 */
export interface Domains {
	spending: Spending;
	income: Income;
	networth: Networth;
	investments: Investments;
	cards: Cards;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "Overview".
 */
export interface Overview {
	by_year: ByYear;
	all_time_by_category: AllTimeByCategory;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "YearSpend".
 */
export interface YearSpend {
	year: Year;
	spent: Spent;
	income: Income1;
	saved: Saved;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "CategoryAmount".
 */
export interface CategoryAmount {
	category: Category;
	amount: Amount;
}
export interface Years1 {
	[k: string]: YearPage;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "YearPage".
 */
export interface YearPage {
	total_spent: TotalSpent;
	total_income: TotalIncome;
	matrix: Matrix;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "MonthMatrixRow".
 */
export interface MonthMatrixRow {
	month: Month;
	spent: Spent1;
	income: Income2;
}
export interface Spent1 {
	[k: string]: number;
}
export interface Months {
	[k: string]: MonthPage;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "MonthPage".
 */
export interface MonthPage {
	total_spent: TotalSpent1;
	total_income: TotalIncome1;
	by_category: ByCategory;
	transactions: Transactions;
	paychecks: Paychecks;
	transfers?: Transfers;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "Txn".
 */
export interface Txn {
	date: Date;
	payee: Payee;
	amount: Amount1;
	category: Category1;
	source: Source;
	pending: Pending;
	locator: Locator;
	bill?: Bill;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "PaycheckOut".
 */
export interface PaycheckOut {
	date: Date1;
	payee: Payee1;
	employer?: Employer;
	gross: Gross;
	deductions: Deductions;
	contributions: Contributions;
	net: Net;
	take_home: TakeHome;
	locator: Locator1;
}
export interface Deductions {
	[k: string]: number;
}
export interface Contributions {
	[k: string]: number;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "Transfer".
 */
export interface Transfer {
	date: Date2;
	payee: Payee2;
	amount: Amount2;
	from_account: FromAccount;
	to_account: ToAccount;
	pending: Pending1;
	locator: Locator2;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "IncomeSection".
 */
export interface IncomeSection {
	by_year: ByYear1;
	by_month: ByMonth;
	recent_paychecks: RecentPaychecks;
}
/**
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "IncomeYear".
 */
export interface IncomeYear {
	year: Year1;
	gross: Gross1;
	net: Net1;
	take_home: TakeHome1;
	deductions: Deductions1;
	contributions: Contributions1;
}
export interface ByMonth {
	[k: string]: number[];
}
/**
 * Reserved: derived assets − liabilities over time. Empty in v1.
 *
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "NetWorthSection".
 */
export interface NetWorthSection {
	[k: string]: unknown;
}
/**
 * Reserved: broker holdings / gain-loss. Empty in v1.
 *
 * This interface was referenced by `DashboardData`'s JSON-Schema
 * via the `definition` "InvestmentsSection".
 */
export interface InvestmentsSection {
	[k: string]: unknown;
}
